# Generated by Django 6.0.6 on 2026-06-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['created_at'], name='pending_jobs_idx'),
        ),
    ]
